### ISSUE TITLE
[0.74] Umbrella issue for Expo-specific debugger picks

### ISSUE THREAD

**Issue by motiz88** [reactwg/react-native-releases#128]
@byCedric is working on a number of PRs to React Native to keep Expo's debugger integration working in 0.74, following changes to implementation details that Expo was previously relying on.

This includes the following PRs (more could be added)

- [x] https://github.com/facebook/react-native/pull/43310
- [x] https://github.com/facebook/react-native/pull/43307
- [x] https://github.com/facebook/react-native/pull/43364
- [x] https://github.com/facebook/react-native/pull/43291

This is an umbrella issue to track this work for 0.74.

NOTE: Beyond just fixing 0.74, the PRs are designed to prevent future breakages from making it to RC.

**Comment by byCedric** [comment]
There is 1 PR more, that unblocks our tunnel/lan/local mode when starting Metro: https://github.com/facebook/react-native/pull/43307

**Comment by cortinico** [comment]
We're going to do RC3 on Monday 11th at 10AM GMT.
Which of those PRs should be included? I assume only https://github.com/facebook/react-native/pull/43310 for now?

**Comment by byCedric** [comment]
All PRs are awaiting review, I'm not sure which one we can merge before the 11th. @cortinico

**Comment by cortinico** [comment]
> All PRs, except that one, are awaiting review. I'm not sure which one we can merge before the 11th. @cortinico

Got it 👍 I'm more wondering if those PRs are meaningful in isolation or they need to be picked all together. If they're isolated, on Monday we'll just pick what we have available in main 👍

**Comment by byCedric** [comment]
The only meaningful one is the API addition: https://github.com/facebook/react-native/pull/43291

The others are small bug fixes and can be done in isolation. We can work around those issues if we know they haven't been merged yet. Eventually we shouldn't have to work around these though, but that's for a time when everything is merged.

**Comment by cortinico** [comment]
We're picking: 
- https://github.com/facebook/react-native/pull/43310
into the release branch. Will be released in RC3

**Comment by huntie** [comment]
All changes picked (will be 0.74 RC4) ✅
